# Generated by Django 2.0.2 on 2018-06-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='URL',
            new_name='url',
        ),
    ]
